// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smart_limiter.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SmartLimiterSpec struct {
	// subset rate-limit,the key is subset name.
	Sets                 map[string]*SmartLimitDescriptors `protobuf:"bytes,2,rep,name=sets,proto3" json:"sets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SmartLimiterSpec) Reset()         { *m = SmartLimiterSpec{} }
func (m *SmartLimiterSpec) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterSpec) ProtoMessage()    {}
func (*SmartLimiterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{0}
}
func (m *SmartLimiterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterSpec.Unmarshal(m, b)
}
func (m *SmartLimiterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterSpec.Marshal(b, m, deterministic)
}
func (m *SmartLimiterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterSpec.Merge(m, src)
}
func (m *SmartLimiterSpec) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterSpec.Size(m)
}
func (m *SmartLimiterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterSpec proto.InternalMessageInfo

func (m *SmartLimiterSpec) GetSets() map[string]*SmartLimitDescriptors {
	if m != nil {
		return m.Sets
	}
	return nil
}

type SmartLimiterStatus struct {
	RatelimitStatus map[string]*SmartLimitDescriptors `protobuf:"bytes,1,rep,name=ratelimitStatus,proto3" json:"ratelimitStatus,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MetricStatus    map[string]string                 `protobuf:"bytes,2,rep,name=metricStatus,proto3" json:"metricStatus,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Deprecated
	ServiceStatus        *SmartLimiterStatus_ServiceStatus `protobuf:"bytes,3,opt,name=serviceStatus,proto3" json:"serviceStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SmartLimiterStatus) Reset()         { *m = SmartLimiterStatus{} }
func (m *SmartLimiterStatus) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus) ProtoMessage()    {}
func (*SmartLimiterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{1}
}
func (m *SmartLimiterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus.Unmarshal(m, b)
}
func (m *SmartLimiterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus.Merge(m, src)
}
func (m *SmartLimiterStatus) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus.Size(m)
}
func (m *SmartLimiterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus proto.InternalMessageInfo

func (m *SmartLimiterStatus) GetRatelimitStatus() map[string]*SmartLimitDescriptors {
	if m != nil {
		return m.RatelimitStatus
	}
	return nil
}

func (m *SmartLimiterStatus) GetMetricStatus() map[string]string {
	if m != nil {
		return m.MetricStatus
	}
	return nil
}

func (m *SmartLimiterStatus) GetServiceStatus() *SmartLimiterStatus_ServiceStatus {
	if m != nil {
		return m.ServiceStatus
	}
	return nil
}

type SmartLimiterStatus_ServiceStatus struct {
	// Deprecated
	Selector map[string]string `protobuf:"bytes,1,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Deprecated
	Listener             []*SmartLimiterStatus_ServiceStatus_Listener `protobuf:"bytes,2,rep,name=listener,proto3" json:"listener,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *SmartLimiterStatus_ServiceStatus) Reset()         { *m = SmartLimiterStatus_ServiceStatus{} }
func (m *SmartLimiterStatus_ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus_ServiceStatus) ProtoMessage()    {}
func (*SmartLimiterStatus_ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{1, 2}
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Unmarshal(m, b)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Merge(m, src)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Size(m)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus_ServiceStatus proto.InternalMessageInfo

func (m *SmartLimiterStatus_ServiceStatus) GetSelector() map[string]string {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *SmartLimiterStatus_ServiceStatus) GetListener() []*SmartLimiterStatus_ServiceStatus_Listener {
	if m != nil {
		return m.Listener
	}
	return nil
}

type SmartLimiterStatus_ServiceStatus_Listener struct {
	// Deprecated
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Deprecated
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) Reset() {
	*m = SmartLimiterStatus_ServiceStatus_Listener{}
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) String() string {
	return proto.CompactTextString(m)
}
func (*SmartLimiterStatus_ServiceStatus_Listener) ProtoMessage() {}
func (*SmartLimiterStatus_ServiceStatus_Listener) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{1, 2, 1}
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Unmarshal(m, b)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Merge(m, src)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Size(m)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener proto.InternalMessageInfo

func (m *SmartLimiterStatus_ServiceStatus_Listener) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type SmartLimitDescriptor struct {
	Condition            string                                `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Action               *SmartLimitDescriptor_Action          `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Match                []*SmartLimitDescriptor_HeaderMatcher `protobuf:"bytes,3,rep,name=match,proto3" json:"match,omitempty"`
	Target               *SmartLimitDescriptor_Target          `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	CustomKey            string                                `protobuf:"bytes,5,opt,name=custom_key,json=customKey,proto3" json:"custom_key,omitempty"`
	CustomValue          string                                `protobuf:"bytes,6,opt,name=custom_value,json=customValue,proto3" json:"custom_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *SmartLimitDescriptor) Reset()         { *m = SmartLimitDescriptor{} }
func (m *SmartLimitDescriptor) String() string { return proto.CompactTextString(m) }
func (*SmartLimitDescriptor) ProtoMessage()    {}
func (*SmartLimitDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{2}
}
func (m *SmartLimitDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimitDescriptor.Unmarshal(m, b)
}
func (m *SmartLimitDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimitDescriptor.Marshal(b, m, deterministic)
}
func (m *SmartLimitDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimitDescriptor.Merge(m, src)
}
func (m *SmartLimitDescriptor) XXX_Size() int {
	return xxx_messageInfo_SmartLimitDescriptor.Size(m)
}
func (m *SmartLimitDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimitDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimitDescriptor proto.InternalMessageInfo

func (m *SmartLimitDescriptor) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *SmartLimitDescriptor) GetAction() *SmartLimitDescriptor_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *SmartLimitDescriptor) GetMatch() []*SmartLimitDescriptor_HeaderMatcher {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *SmartLimitDescriptor) GetTarget() *SmartLimitDescriptor_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SmartLimitDescriptor) GetCustomKey() string {
	if m != nil {
		return m.CustomKey
	}
	return ""
}

func (m *SmartLimitDescriptor) GetCustomValue() string {
	if m != nil {
		return m.CustomValue
	}
	return ""
}

type SmartLimitDescriptor_HeaderMatcher struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// If specified, header match will be performed based on the value of the header.
	// This field is deprecated. Please use :ref:`string_match <envoy_v3_api_field_config.route.v3.HeaderMatcher.string_match>`.
	ExactMatch string `protobuf:"bytes,2,opt,name=exact_match,json=exactMatch,proto3" json:"exact_match,omitempty"`
	// If specified, this regex string is a regular expression rule which implies the entire request
	// header value must match the regex. The rule will not match if only a subsequence of the
	// request header value matches the regex.
	// This field is deprecated. Please use :ref:`string_match <envoy_v3_api_field_config.route.v3.HeaderMatcher.string_match>`.
	RegexMatch string `protobuf:"bytes,3,opt,name=regex_match,json=regexMatch,proto3" json:"regex_match,omitempty"`
	// If specified as true, header match will be performed based on whether the header is in the
	// request. If specified as false, header match will be performed based on whether the header is absent.
	PresentMatch string `protobuf:"bytes,4,opt,name=present_match,json=presentMatch,proto3" json:"present_match,omitempty"`
	// * The prefix *abcd* matches the value *abcdxyz*, but not for *abcxyz*.
	PrefixMatch string `protobuf:"bytes,5,opt,name=prefix_match,json=prefixMatch,proto3" json:"prefix_match,omitempty"`
	// * The suffix *abcd* matches the value *xyzabcd*, but not for *xyzbcd*.
	SuffixMatch string `protobuf:"bytes,6,opt,name=suffix_match,json=suffixMatch,proto3" json:"suffix_match,omitempty"`
	// If specified, the match result will be inverted before checking. Defaults to false.
	//
	// Examples:
	//
	// * The regex ``\d{3}`` does not match the value *1234*, so it will match when inverted.
	InvertMatch          string   `protobuf:"bytes,7,opt,name=invert_match,json=invertMatch,proto3" json:"invert_match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartLimitDescriptor_HeaderMatcher) Reset()         { *m = SmartLimitDescriptor_HeaderMatcher{} }
func (m *SmartLimitDescriptor_HeaderMatcher) String() string { return proto.CompactTextString(m) }
func (*SmartLimitDescriptor_HeaderMatcher) ProtoMessage()    {}
func (*SmartLimitDescriptor_HeaderMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{2, 0}
}
func (m *SmartLimitDescriptor_HeaderMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimitDescriptor_HeaderMatcher.Unmarshal(m, b)
}
func (m *SmartLimitDescriptor_HeaderMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimitDescriptor_HeaderMatcher.Marshal(b, m, deterministic)
}
func (m *SmartLimitDescriptor_HeaderMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimitDescriptor_HeaderMatcher.Merge(m, src)
}
func (m *SmartLimitDescriptor_HeaderMatcher) XXX_Size() int {
	return xxx_messageInfo_SmartLimitDescriptor_HeaderMatcher.Size(m)
}
func (m *SmartLimitDescriptor_HeaderMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimitDescriptor_HeaderMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimitDescriptor_HeaderMatcher proto.InternalMessageInfo

func (m *SmartLimitDescriptor_HeaderMatcher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartLimitDescriptor_HeaderMatcher) GetExactMatch() string {
	if m != nil {
		return m.ExactMatch
	}
	return ""
}

func (m *SmartLimitDescriptor_HeaderMatcher) GetRegexMatch() string {
	if m != nil {
		return m.RegexMatch
	}
	return ""
}

func (m *SmartLimitDescriptor_HeaderMatcher) GetPresentMatch() string {
	if m != nil {
		return m.PresentMatch
	}
	return ""
}

func (m *SmartLimitDescriptor_HeaderMatcher) GetPrefixMatch() string {
	if m != nil {
		return m.PrefixMatch
	}
	return ""
}

func (m *SmartLimitDescriptor_HeaderMatcher) GetSuffixMatch() string {
	if m != nil {
		return m.SuffixMatch
	}
	return ""
}

func (m *SmartLimitDescriptor_HeaderMatcher) GetInvertMatch() string {
	if m != nil {
		return m.InvertMatch
	}
	return ""
}

type SmartLimitDescriptor_Action struct {
	Quota                string    `protobuf:"bytes,1,opt,name=quota,proto3" json:"quota,omitempty"`
	FillInterval         *Duration `protobuf:"bytes,2,opt,name=fill_interval,json=fillInterval,proto3" json:"fill_interval,omitempty"`
	Strategy             string    `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	RateLimitService     string    `protobuf:"bytes,4,opt,name=rate_limit_service,json=rateLimitService,proto3" json:"rate_limit_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SmartLimitDescriptor_Action) Reset()         { *m = SmartLimitDescriptor_Action{} }
func (m *SmartLimitDescriptor_Action) String() string { return proto.CompactTextString(m) }
func (*SmartLimitDescriptor_Action) ProtoMessage()    {}
func (*SmartLimitDescriptor_Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{2, 1}
}
func (m *SmartLimitDescriptor_Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimitDescriptor_Action.Unmarshal(m, b)
}
func (m *SmartLimitDescriptor_Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimitDescriptor_Action.Marshal(b, m, deterministic)
}
func (m *SmartLimitDescriptor_Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimitDescriptor_Action.Merge(m, src)
}
func (m *SmartLimitDescriptor_Action) XXX_Size() int {
	return xxx_messageInfo_SmartLimitDescriptor_Action.Size(m)
}
func (m *SmartLimitDescriptor_Action) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimitDescriptor_Action.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimitDescriptor_Action proto.InternalMessageInfo

func (m *SmartLimitDescriptor_Action) GetQuota() string {
	if m != nil {
		return m.Quota
	}
	return ""
}

func (m *SmartLimitDescriptor_Action) GetFillInterval() *Duration {
	if m != nil {
		return m.FillInterval
	}
	return nil
}

func (m *SmartLimitDescriptor_Action) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *SmartLimitDescriptor_Action) GetRateLimitService() string {
	if m != nil {
		return m.RateLimitService
	}
	return ""
}

type SmartLimitDescriptor_Target struct {
	Direction            string   `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Route                string   `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Host                 string   `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartLimitDescriptor_Target) Reset()         { *m = SmartLimitDescriptor_Target{} }
func (m *SmartLimitDescriptor_Target) String() string { return proto.CompactTextString(m) }
func (*SmartLimitDescriptor_Target) ProtoMessage()    {}
func (*SmartLimitDescriptor_Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{2, 2}
}
func (m *SmartLimitDescriptor_Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimitDescriptor_Target.Unmarshal(m, b)
}
func (m *SmartLimitDescriptor_Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimitDescriptor_Target.Marshal(b, m, deterministic)
}
func (m *SmartLimitDescriptor_Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimitDescriptor_Target.Merge(m, src)
}
func (m *SmartLimitDescriptor_Target) XXX_Size() int {
	return xxx_messageInfo_SmartLimitDescriptor_Target.Size(m)
}
func (m *SmartLimitDescriptor_Target) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimitDescriptor_Target.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimitDescriptor_Target proto.InternalMessageInfo

func (m *SmartLimitDescriptor_Target) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *SmartLimitDescriptor_Target) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *SmartLimitDescriptor_Target) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *SmartLimitDescriptor_Target) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type SmartLimitDescriptors struct {
	// Description of current rate-limit
	Descriptor_          []*SmartLimitDescriptor `protobuf:"bytes,4,rep,name=descriptor,proto3" json:"descriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SmartLimitDescriptors) Reset()         { *m = SmartLimitDescriptors{} }
func (m *SmartLimitDescriptors) String() string { return proto.CompactTextString(m) }
func (*SmartLimitDescriptors) ProtoMessage()    {}
func (*SmartLimitDescriptors) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{3}
}
func (m *SmartLimitDescriptors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimitDescriptors.Unmarshal(m, b)
}
func (m *SmartLimitDescriptors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimitDescriptors.Marshal(b, m, deterministic)
}
func (m *SmartLimitDescriptors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimitDescriptors.Merge(m, src)
}
func (m *SmartLimitDescriptors) XXX_Size() int {
	return xxx_messageInfo_SmartLimitDescriptors.Size(m)
}
func (m *SmartLimitDescriptors) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimitDescriptors.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimitDescriptors proto.InternalMessageInfo

func (m *SmartLimitDescriptors) GetDescriptor_() []*SmartLimitDescriptor {
	if m != nil {
		return m.Descriptor_
	}
	return nil
}

type Duration struct {
	// Signed seconds of the span of time. Must be from -315,576,000,000
	// to +315,576,000,000 inclusive. Note: these bounds are computed from:
	// 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Signed fractions of a second at nanosecond resolution of the span
	// of time. Durations less than one second are represented with a 0
	// `seconds` field and a positive or negative `nanos` field. For durations
	// of one second or more, a non-zero value for the `nanos` field must be
	// of the same sign as the `seconds` field. Must be from -999,999,999
	// to +999,999,999 inclusive.
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_452a0625a4f6276b, []int{4}
}
func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Duration) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

func init() {
	proto.RegisterType((*SmartLimiterSpec)(nil), "slime.microservice.v1alpha1.SmartLimiterSpec")
	proto.RegisterMapType((map[string]*SmartLimitDescriptors)(nil), "slime.microservice.v1alpha1.SmartLimiterSpec.SetsEntry")
	proto.RegisterType((*SmartLimiterStatus)(nil), "slime.microservice.v1alpha1.SmartLimiterStatus")
	proto.RegisterMapType((map[string]string)(nil), "slime.microservice.v1alpha1.SmartLimiterStatus.MetricStatusEntry")
	proto.RegisterMapType((map[string]*SmartLimitDescriptors)(nil), "slime.microservice.v1alpha1.SmartLimiterStatus.RatelimitStatusEntry")
	proto.RegisterType((*SmartLimiterStatus_ServiceStatus)(nil), "slime.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus")
	proto.RegisterMapType((map[string]string)(nil), "slime.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus.SelectorEntry")
	proto.RegisterType((*SmartLimiterStatus_ServiceStatus_Listener)(nil), "slime.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus.Listener")
	proto.RegisterType((*SmartLimitDescriptor)(nil), "slime.microservice.v1alpha1.SmartLimitDescriptor")
	proto.RegisterType((*SmartLimitDescriptor_HeaderMatcher)(nil), "slime.microservice.v1alpha1.SmartLimitDescriptor.HeaderMatcher")
	proto.RegisterType((*SmartLimitDescriptor_Action)(nil), "slime.microservice.v1alpha1.SmartLimitDescriptor.Action")
	proto.RegisterType((*SmartLimitDescriptor_Target)(nil), "slime.microservice.v1alpha1.SmartLimitDescriptor.Target")
	proto.RegisterType((*SmartLimitDescriptors)(nil), "slime.microservice.v1alpha1.SmartLimitDescriptors")
	proto.RegisterType((*Duration)(nil), "slime.microservice.v1alpha1.Duration")
}

func init() { proto.RegisterFile("smart_limiter.proto", fileDescriptor_452a0625a4f6276b) }

var fileDescriptor_452a0625a4f6276b = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdb, 0x6e, 0x13, 0x49,
	0x10, 0xd5, 0xf8, 0x16, 0xbb, 0x6c, 0x6b, 0xb3, 0xbd, 0x59, 0x69, 0x34, 0xbb, 0xab, 0x4d, 0xbc,
	0x5a, 0x29, 0x0f, 0xbb, 0x63, 0xd9, 0x79, 0x20, 0x0a, 0x42, 0x51, 0x50, 0x40, 0x81, 0x24, 0x12,
	0x8c, 0x81, 0x07, 0x5e, 0xac, 0xce, 0xb8, 0xe2, 0x34, 0x99, 0x8b, 0xe9, 0xee, 0xb1, 0xe2, 0x77,
	0x3e, 0x89, 0xcf, 0x80, 0x0f, 0xe0, 0x3b, 0xf8, 0x01, 0xd4, 0x97, 0x99, 0xd8, 0xc1, 0x8a, 0x62,
	0x22, 0x5e, 0xac, 0xee, 0x33, 0x55, 0xa7, 0xea, 0xd4, 0x65, 0x3c, 0xf0, 0x9b, 0x88, 0x29, 0x97,
	0xc3, 0x88, 0xc5, 0x4c, 0x22, 0xf7, 0x27, 0x3c, 0x95, 0x29, 0xf9, 0x43, 0x44, 0x2c, 0x46, 0x3f,
	0x66, 0x21, 0x4f, 0x05, 0xf2, 0x29, 0x0b, 0xd1, 0x9f, 0xf6, 0x68, 0x34, 0xb9, 0xa0, 0xbd, 0xce,
	0x27, 0x07, 0xd6, 0x07, 0xca, 0xe9, 0xc4, 0xf8, 0x0c, 0x26, 0x18, 0x92, 0x63, 0xa8, 0x08, 0x94,
	0xc2, 0x2d, 0x6d, 0x96, 0xb7, 0x9b, 0xfd, 0x07, 0xfe, 0x2d, 0x04, 0xfe, 0x4d, 0x67, 0x7f, 0x80,
	0x52, 0x3c, 0x49, 0x24, 0x9f, 0x05, 0x9a, 0xc4, 0xbb, 0x84, 0x46, 0x01, 0x91, 0x75, 0x28, 0x5f,
	0xe2, 0xcc, 0x75, 0x36, 0x9d, 0xed, 0x46, 0xa0, 0x8e, 0xe4, 0x08, 0xaa, 0x53, 0x1a, 0x65, 0xe8,
	0x96, 0x36, 0x9d, 0xed, 0x66, 0xbf, 0x7f, 0xc7, 0x60, 0x87, 0x28, 0x42, 0xce, 0x26, 0x32, 0xe5,
	0x22, 0x30, 0x04, 0x7b, 0xa5, 0x5d, 0xa7, 0xf3, 0xa5, 0x06, 0x64, 0x21, 0x23, 0x49, 0x65, 0x26,
	0x48, 0x02, 0xbf, 0x70, 0x2a, 0x51, 0xd7, 0xc5, 0x40, 0xae, 0xa3, 0xb5, 0x1d, 0xde, 0x5d, 0x9b,
	0x76, 0xf3, 0x83, 0x45, 0x1a, 0x23, 0xf4, 0x26, 0x39, 0x41, 0x68, 0xc5, 0x28, 0x39, 0x0b, 0x6d,
	0x30, 0x53, 0xc8, 0x83, 0x55, 0x83, 0x9d, 0xce, 0x71, 0x98, 0x48, 0x0b, 0xb4, 0x24, 0x84, 0xb6,
	0xa5, 0xb1, 0x71, 0xca, 0xba, 0x86, 0x8f, 0x56, 0x8d, 0x33, 0x98, 0x27, 0x09, 0x16, 0x39, 0xbd,
	0x29, 0x6c, 0x2c, 0x13, 0xfd, 0xb3, 0x5b, 0xe9, 0xed, 0xc3, 0xaf, 0xdf, 0xe9, 0x5f, 0x12, 0x74,
	0x63, 0x3e, 0x68, 0x63, 0x9e, 0xe0, 0x73, 0x09, 0xda, 0x0b, 0xca, 0xc8, 0x18, 0xea, 0x02, 0x23,
	0x0c, 0x65, 0xca, 0x6d, 0xff, 0x8f, 0xef, 0x55, 0x2a, 0x7f, 0x60, 0xd9, 0x4c, 0x73, 0x0a, 0x72,
	0x72, 0x06, 0xf5, 0x88, 0x09, 0x89, 0x09, 0x72, 0xdb, 0xfb, 0xa7, 0xf7, 0x0b, 0x74, 0x62, 0xd9,
	0x82, 0x82, 0xd7, 0x7b, 0xa8, 0xd4, 0xcd, 0x85, 0x5f, 0xa9, 0x36, 0x7d, 0xa8, 0xe7, 0x94, 0x84,
	0x40, 0x25, 0xa1, 0x31, 0x5a, 0x47, 0x7d, 0x56, 0xd8, 0x24, 0xe5, 0x52, 0x3b, 0xb6, 0x03, 0x7d,
	0xee, 0x7c, 0x58, 0x83, 0x8d, 0x65, 0x5d, 0x23, 0x7f, 0x42, 0x23, 0x4c, 0x93, 0x11, 0x93, 0x2c,
	0x4d, 0x2c, 0xcb, 0x35, 0x40, 0x5e, 0x40, 0x8d, 0x86, 0xfa, 0x91, 0x19, 0x8b, 0xdd, 0x95, 0xc7,
	0xc2, 0x3f, 0xd0, 0xfe, 0x81, 0xe5, 0x21, 0xaf, 0xa1, 0x1a, 0x53, 0x19, 0x5e, 0xb8, 0x65, 0x5d,
	0xda, 0xfd, 0xd5, 0x09, 0x8f, 0x90, 0x8e, 0x90, 0x9f, 0x2a, 0x12, 0xe4, 0x81, 0x61, 0x53, 0x89,
	0x4a, 0xca, 0xc7, 0x28, 0xdd, 0xca, 0x8f, 0x26, 0xfa, 0x4a, 0xfb, 0x07, 0x96, 0x87, 0xfc, 0x05,
	0x10, 0x66, 0x42, 0xa6, 0xf1, 0x50, 0x35, 0xa6, 0x6a, 0x2b, 0xa3, 0x91, 0x63, 0x9c, 0x91, 0x2d,
	0x68, 0xd9, 0xc7, 0xa6, 0x4b, 0x35, 0x6d, 0xd0, 0x34, 0xd8, 0x1b, 0x05, 0x79, 0x5f, 0x1d, 0x68,
	0x2f, 0x24, 0xbb, 0xb4, 0x5b, 0x7f, 0x43, 0x13, 0xaf, 0x68, 0x28, 0x87, 0xa6, 0x2c, 0xa6, 0xdb,
	0xa0, 0x21, 0xed, 0xa6, 0x0c, 0x38, 0x8e, 0xf1, 0x6a, 0x98, 0xd7, 0x4d, 0x1b, 0x68, 0xc8, 0x18,
	0xfc, 0x03, 0xed, 0x09, 0x47, 0x81, 0x49, 0xce, 0x51, 0xd1, 0x26, 0x2d, 0x0b, 0x1a, 0xa3, 0x2d,
	0x50, 0xf7, 0x73, 0x96, 0xd3, 0x18, 0x41, 0x4d, 0x83, 0x15, 0x26, 0x22, 0x3b, 0xbf, 0x36, 0xb1,
	0x92, 0x0c, 0x56, 0x98, 0xb0, 0x64, 0x8a, 0x3c, 0x8f, 0xb4, 0x66, 0x4c, 0x0c, 0xa6, 0x4d, 0xbc,
	0x8f, 0x0e, 0xd4, 0x4c, 0xcf, 0xd5, 0x08, 0xbf, 0xcf, 0x52, 0x49, 0xad, 0x5e, 0x73, 0x21, 0xcf,
	0xa1, 0x7d, 0xce, 0xa2, 0x68, 0xc8, 0x12, 0x89, 0x7c, 0x4a, 0x23, 0x3b, 0x5a, 0xff, 0xde, 0xda,
	0xb1, 0xc3, 0x8c, 0x53, 0x3d, 0x47, 0x2d, 0xe5, 0xfb, 0xcc, 0xba, 0x12, 0x0f, 0xea, 0x42, 0xaa,
	0x17, 0xf8, 0x78, 0x66, 0x0b, 0x53, 0xdc, 0xc9, 0x7f, 0x40, 0xd4, 0xc9, 0xfc, 0xa1, 0x0e, 0x2d,
	0xa3, 0xad, 0xcd, 0xba, 0x7a, 0xa2, 0x07, 0xc0, 0xae, 0xaa, 0x37, 0x82, 0x9a, 0x19, 0x00, 0xb5,
	0x11, 0x23, 0xc6, 0x31, 0x9c, 0xdf, 0x88, 0x02, 0x58, 0x58, 0xae, 0xaa, 0x59, 0x2e, 0xa5, 0x93,
	0xa7, 0x99, 0x44, 0x9b, 0x82, 0xb9, 0x28, 0xcb, 0x8b, 0x54, 0x48, 0x1b, 0x51, 0x9f, 0x3b, 0xef,
	0xe0, 0xf7, 0xa5, 0xef, 0x4e, 0xf2, 0x12, 0x60, 0x54, 0x5c, 0xdd, 0x8a, 0xde, 0x8d, 0xde, 0xca,
	0x33, 0x1c, 0xcc, 0x91, 0x74, 0xf6, 0xa0, 0x9e, 0x57, 0x8d, 0xb8, 0xb0, 0x26, 0x50, 0xad, 0xb5,
	0xd0, 0x8a, 0xca, 0x41, 0x7e, 0x55, 0xb9, 0x27, 0x34, 0x49, 0x85, 0x15, 0x64, 0x2e, 0x8f, 0x77,
	0xde, 0xf6, 0x4c, 0x6c, 0x96, 0x76, 0xf5, 0xc1, 0xfc, 0xfe, 0x1f, 0xa7, 0xa3, 0x2c, 0x42, 0xd1,
	0xb5, 0x1f, 0x29, 0x5d, 0x3a, 0x61, 0xdd, 0x3c, 0xa3, 0xb3, 0x9a, 0xfe, 0x64, 0xd9, 0xf9, 0x16,
	0x00, 0x00, 0xff, 0xff, 0x25, 0x56, 0x76, 0x94, 0xc9, 0x08, 0x00, 0x00,
}
