// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/microservice/v1alpha1/smart_limiter.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SmartLimiterSpec struct {
	RatelimitConfig      *FlowControlConfSpec `protobuf:"bytes,1,opt,name=ratelimitConfig,proto3" json:"ratelimitConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SmartLimiterSpec) Reset()         { *m = SmartLimiterSpec{} }
func (m *SmartLimiterSpec) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterSpec) ProtoMessage()    {}
func (*SmartLimiterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{0}
}

func (m *SmartLimiterSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterSpec.Unmarshal(m, b)
}
func (m *SmartLimiterSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterSpec.Marshal(b, m, deterministic)
}
func (m *SmartLimiterSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterSpec.Merge(m, src)
}
func (m *SmartLimiterSpec) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterSpec.Size(m)
}
func (m *SmartLimiterSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterSpec proto.InternalMessageInfo

func (m *SmartLimiterSpec) GetRatelimitConfig() *FlowControlConfSpec {
	if m != nil {
		return m.RatelimitConfig
	}
	return nil
}

type SmartLimiterStatus struct {
	RatelimitStatus      *FlowControlConfStatus            `protobuf:"bytes,1,opt,name=ratelimitStatus,proto3" json:"ratelimitStatus,omitempty"`
	EndPointStatus       map[string]string                 `protobuf:"bytes,2,rep,name=endPointStatus,proto3" json:"endPointStatus,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ServiceStatus        *SmartLimiterStatus_ServiceStatus `protobuf:"bytes,3,opt,name=serviceStatus,proto3" json:"serviceStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SmartLimiterStatus) Reset()         { *m = SmartLimiterStatus{} }
func (m *SmartLimiterStatus) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus) ProtoMessage()    {}
func (*SmartLimiterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{1}
}

func (m *SmartLimiterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus.Unmarshal(m, b)
}
func (m *SmartLimiterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus.Merge(m, src)
}
func (m *SmartLimiterStatus) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus.Size(m)
}
func (m *SmartLimiterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus proto.InternalMessageInfo

func (m *SmartLimiterStatus) GetRatelimitStatus() *FlowControlConfStatus {
	if m != nil {
		return m.RatelimitStatus
	}
	return nil
}

func (m *SmartLimiterStatus) GetEndPointStatus() map[string]string {
	if m != nil {
		return m.EndPointStatus
	}
	return nil
}

func (m *SmartLimiterStatus) GetServiceStatus() *SmartLimiterStatus_ServiceStatus {
	if m != nil {
		return m.ServiceStatus
	}
	return nil
}

type SmartLimiterStatus_ServiceStatus struct {
	Selector             map[string]string                            `protobuf:"bytes,1,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Listener             []*SmartLimiterStatus_ServiceStatus_Listener `protobuf:"bytes,2,rep,name=listener,proto3" json:"listener,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *SmartLimiterStatus_ServiceStatus) Reset()         { *m = SmartLimiterStatus_ServiceStatus{} }
func (m *SmartLimiterStatus_ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus_ServiceStatus) ProtoMessage()    {}
func (*SmartLimiterStatus_ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{1, 1}
}

func (m *SmartLimiterStatus_ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Unmarshal(m, b)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Merge(m, src)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus.Size(m)
}
func (m *SmartLimiterStatus_ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus_ServiceStatus proto.InternalMessageInfo

func (m *SmartLimiterStatus_ServiceStatus) GetSelector() map[string]string {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *SmartLimiterStatus_ServiceStatus) GetListener() []*SmartLimiterStatus_ServiceStatus_Listener {
	if m != nil {
		return m.Listener
	}
	return nil
}

type SmartLimiterStatus_ServiceStatus_Listener struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) Reset() {
	*m = SmartLimiterStatus_ServiceStatus_Listener{}
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) String() string { return proto.CompactTextString(m) }
func (*SmartLimiterStatus_ServiceStatus_Listener) ProtoMessage()    {}
func (*SmartLimiterStatus_ServiceStatus_Listener) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bfc6c51416fcda, []int{1, 1, 1}
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Unmarshal(m, b)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Marshal(b, m, deterministic)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Merge(m, src)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_Size() int {
	return xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.Size(m)
}
func (m *SmartLimiterStatus_ServiceStatus_Listener) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener.DiscardUnknown(m)
}

var xxx_messageInfo_SmartLimiterStatus_ServiceStatus_Listener proto.InternalMessageInfo

func (m *SmartLimiterStatus_ServiceStatus_Listener) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SmartLimiterStatus_ServiceStatus_Listener) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*SmartLimiterSpec)(nil), "netease.microservice.v1alpha1.SmartLimiterSpec")
	proto.RegisterType((*SmartLimiterStatus)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus")
	proto.RegisterMapType((map[string]string)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.EndPointStatusEntry")
	proto.RegisterType((*SmartLimiterStatus_ServiceStatus)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus")
	proto.RegisterMapType((map[string]string)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus.SelectorEntry")
	proto.RegisterType((*SmartLimiterStatus_ServiceStatus_Listener)(nil), "netease.microservice.v1alpha1.SmartLimiterStatus.ServiceStatus.Listener")
}

func init() {
	proto.RegisterFile("pkg/apis/microservice/v1alpha1/smart_limiter.proto", fileDescriptor_76bfc6c51416fcda)
}

var fileDescriptor_76bfc6c51416fcda = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x8a, 0x13, 0x41,
	0x10, 0xc6, 0x99, 0xc4, 0x95, 0xd8, 0x12, 0x5d, 0x5a, 0x05, 0x19, 0x10, 0x96, 0x3d, 0x79, 0xea,
	0x61, 0x47, 0x41, 0x51, 0x41, 0xdc, 0x10, 0xf1, 0x10, 0x21, 0x4c, 0x6e, 0x5e, 0x42, 0xdb, 0x5b,
	0xd9, 0x6d, 0xb6, 0xa7, 0x7b, 0xe8, 0xee, 0x8c, 0xce, 0xd1, 0x07, 0xf0, 0xe1, 0x7c, 0x15, 0x9f,
	0xc0, 0xfe, 0x33, 0x09, 0x33, 0x71, 0xd9, 0x25, 0xe4, 0x56, 0x55, 0x50, 0xbf, 0xef, 0xab, 0x9a,
	0x9a, 0x46, 0x79, 0x75, 0x7d, 0x99, 0xd1, 0x8a, 0x9b, 0xac, 0xe4, 0x4c, 0x2b, 0x03, 0xba, 0xe6,
	0x0c, 0xb2, 0xfa, 0x8c, 0x8a, 0xea, 0x8a, 0x9e, 0x65, 0xa6, 0xa4, 0xda, 0x2e, 0x05, 0x2f, 0xb9,
	0x05, 0x4d, 0x2a, 0xad, 0xac, 0xc2, 0x2f, 0x24, 0x58, 0xa0, 0x06, 0x48, 0xb7, 0x85, 0x6c, 0x5a,
	0xd2, 0x37, 0x77, 0x20, 0x85, 0x62, 0x54, 0x2c, 0x57, 0x42, 0xfd, 0x58, 0x32, 0x25, 0xad, 0x56,
	0x22, 0x72, 0x4f, 0x7f, 0x25, 0xe8, 0x78, 0xe1, 0xf5, 0x66, 0x51, 0x6e, 0x51, 0x01, 0xc3, 0x25,
	0x7a, 0xac, 0xa9, 0x85, 0xe0, 0x60, 0xa2, 0xe4, 0x8a, 0x5f, 0x3e, 0x4f, 0x4e, 0x92, 0x97, 0x0f,
	0xf3, 0x09, 0x01, 0x59, 0xab, 0x86, 0xb0, 0x50, 0x24, 0x2b, 0x2e, 0xbc, 0xc3, 0x2b, 0x6b, 0x2b,
	0x72, 0x83, 0x42, 0x9d, 0x93, 0xcf, 0x2e, 0x9f, 0xc4, 0xd4, 0x83, 0x3c, 0xbd, 0xd8, 0x65, 0x9f,
	0xfe, 0x3d, 0x42, 0xb8, 0xe7, 0xc1, 0x52, 0xbb, 0x36, 0x58, 0x75, 0x5c, 0xc4, 0x52, 0xeb, 0x62,
	0x7a, 0xa8, 0x8b, 0x00, 0x2b, 0x76, 0xe9, 0x6e, 0xec, 0x47, 0x20, 0x2f, 0xe6, 0x8a, 0xcb, 0x8d,
	0xde, 0xe0, 0x64, 0x18, 0xf4, 0x6e, 0x5d, 0x3e, 0xf9, 0xdf, 0x3b, 0x99, 0xf6, 0x38, 0x53, 0x27,
	0xdd, 0x14, 0x3b, 0x70, 0x0c, 0x68, 0xdc, 0xa2, 0x5a, 0xb5, 0x61, 0x98, 0xee, 0xe3, 0xfe, 0x6a,
	0x8b, 0x2e, 0xa6, 0xe8, 0x53, 0xd3, 0x4f, 0xe8, 0xc9, 0x0d, 0x6e, 0xf0, 0x31, 0x1a, 0x5e, 0x43,
	0x13, 0x36, 0xfa, 0xa0, 0xf0, 0x21, 0x7e, 0x8a, 0x8e, 0x6a, 0x2a, 0xd6, 0xe0, 0xa6, 0xf6, 0xb5,
	0x98, 0xbc, 0x1b, 0xbc, 0x4d, 0xd2, 0x3f, 0x03, 0x34, 0xee, 0x69, 0x60, 0x8e, 0x46, 0x06, 0x04,
	0x30, 0xab, 0xb4, 0x43, 0xf8, 0x25, 0x7d, 0x3d, 0xd0, 0xb6, 0xcb, 0x22, 0x2f, 0x2e, 0x6b, 0x8b,
	0xc7, 0x17, 0x68, 0x24, 0xb8, 0xb1, 0x20, 0x41, 0xb7, 0xdf, 0xe3, 0xcb, 0xa1, 0x52, 0xb3, 0x96,
	0x57, 0x6c, 0xc9, 0xe9, 0x7b, 0x3f, 0x61, 0xc7, 0xc0, 0x5e, 0xfb, 0xc9, 0xd1, 0x68, 0x83, 0xc4,
	0x18, 0xdd, 0x93, 0xb4, 0x84, 0xb6, 0x31, 0xc4, 0xbe, 0x56, 0x29, 0x6d, 0x43, 0xe3, 0xb8, 0x08,
	0xf1, 0xf9, 0xef, 0x04, 0x7d, 0xe0, 0x2a, 0x5e, 0xb2, 0xfb, 0x15, 0x7f, 0x36, 0x7b, 0x1e, 0xf5,
	0xf9, 0xb3, 0x99, 0x2f, 0x77, 0x4e, 0x7b, 0xee, 0x7f, 0xe8, 0x79, 0xf2, 0xed, 0x75, 0xb3, 0x96,
	0xdb, 0x0d, 0x31, 0x55, 0x66, 0xc6, 0x1d, 0x39, 0x64, 0xb7, 0xbf, 0x10, 0xdf, 0xef, 0x87, 0xf7,
	0xe0, 0xd5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x77, 0x04, 0xe7, 0x9d, 0x04, 0x00, 0x00,
}
